export * from './obj.interface'
export * from './genre.interface'
export * from './movie.interface/movie.interface'
export * from './movie.interface/production_companies.interface'
export * from './movie.interface/production_countries.interface'
export * from './movie-card.interface'
export * from './video.interface'
export * from './movie.interface/movie_obj.interface'
